/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author mantr
 */
public class AlternateMedicinePage extends javax.swing.JPanel {

    /**
     * Creates new form AlternateMedicineJPanel
     */
    public AlternateMedicinePage(AlternateMedicinePage alternateMedicinePage, JPanel Rightpaneldashboard) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alternatemedrightpanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        DisplayNameTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DiseaseListComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AlternateMedicineTable = new javax.swing.JTable();
        ViewDetailsBtn = new javax.swing.JButton();
        ConsultDoctorBtn = new javax.swing.JButton();
        SearchSaltOrMedicineTxt = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(null);
        jPanel1.add(DisplayNameTxt);
        DisplayNameTxt.setBounds(10, 30, 204, 41);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search For Alternate Medicine");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(94, 89, 525, 55);

        jLabel2.setText("Select Disease");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 196, 102, 33);

        DiseaseListComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(DiseaseListComboBox);
        DiseaseListComboBox.setBounds(116, 196, 133, 33);

        jLabel3.setText("Search By Salt or Medicine Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(298, 196, 166, 33);

        AlternateMedicineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Containing salts", "Price", "Medicine Type", "Disease Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AlternateMedicineTable.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(AlternateMedicineTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(21, 247, 656, 234);

        ViewDetailsBtn.setText("View Details");
        jPanel1.add(ViewDetailsBtn);
        ViewDetailsBtn.setBounds(368, 502, 185, 36);

        ConsultDoctorBtn.setText("Consult Physician");
        ConsultDoctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultDoctorBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ConsultDoctorBtn);
        ConsultDoctorBtn.setBounds(111, 502, 171, 36);

        SearchSaltOrMedicineTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchSaltOrMedicineTxtActionPerformed(evt);
            }
        });
        jPanel1.add(SearchSaltOrMedicineTxt);
        SearchSaltOrMedicineTxt.setBounds(474, 196, 203, 33);

        javax.swing.GroupLayout alternatemedrightpanelLayout = new javax.swing.GroupLayout(alternatemedrightpanel);
        alternatemedrightpanel.setLayout(alternatemedrightpanelLayout);
        alternatemedrightpanelLayout.setHorizontalGroup(
            alternatemedrightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
        );
        alternatemedrightpanelLayout.setVerticalGroup(
            alternatemedrightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alternatemedrightpanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(alternatemedrightpanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultDoctorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultDoctorBtnActionPerformed
        // TODO add your handling code here:

        //        CreateAirplanePage createAirplanePage = new CreateAirplanePage(rightPanel,airlineDirectory);
        //        rightPanel.add("AirlineLandingPageJPanel",createAirplanePage);
        //        CardLayout layout = (CardLayout)rightPanel.getLayout();
        //        layout.next(rightPanel);

        ConsultDoctorPage consultDoctorPage = new ConsultDoctorPage();
      //  alternatemedrightpanel.add("");
    }//GEN-LAST:event_ConsultDoctorBtnActionPerformed

    private void SearchSaltOrMedicineTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchSaltOrMedicineTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchSaltOrMedicineTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AlternateMedicineTable;
    private javax.swing.JButton ConsultDoctorBtn;
    private javax.swing.JComboBox DiseaseListComboBox;
    private javax.swing.JLabel DisplayNameTxt;
    private javax.swing.JTextField SearchSaltOrMedicineTxt;
    private javax.swing.JButton ViewDetailsBtn;
    private javax.swing.JPanel alternatemedrightpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
