/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.Enterprise.Enterprise;
import Business.Medicine.Medicine;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.PharmacistOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CustomerWorkRequest;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author mantr
 */
public class DoctorConsultationFormPage extends javax.swing.JPanel {

    /**
     * Creates new form DoctorConsultationFormJPanel
     */
    JPanel rightPanel;
    ArrayList<Medicine> list;
    private UserAccount account;
    private Enterprise enterprise;
    public DoctorConsultationFormPage(JPanel rightPanel,ArrayList<Medicine> list,UserAccount account,Enterprise enterprise) {
        initComponents();
        this.rightPanel=rightPanel;
        this.list=list;
        this.account=account;
        this.enterprise=enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Messagetxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        requestDoctorBtn = new javax.swing.JButton();

        Messagetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MessagetxtActionPerformed(evt);
            }
        });

        jLabel1.setText("Alternative Medicines");

        requestDoctorBtn.setText("Request");
        requestDoctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestDoctorBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addComponent(Messagetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(requestDoctorBtn)
                .addGap(274, 274, 274))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Messagetxt)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addComponent(requestDoctorBtn)
                .addContainerGap(288, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MessagetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessagetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MessagetxtActionPerformed

    private void requestDoctorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestDoctorBtnActionPerformed
        // TODO add your handling code here:
        
        String message = Messagetxt.getText();
        
        CustomerWorkRequest request = new CustomerWorkRequest();
        request.setMessage(message);

        request.setSender(account);
        request.setStatus("Sent");
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof DoctorOrganization){
                org = organization;
                System.out.println("Yeah bitches!!");
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
            System.out.println("Yeah bitches!!");
        }
        
        
    }//GEN-LAST:event_requestDoctorBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Messagetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton requestDoctorBtn;
    // End of variables declaration//GEN-END:variables
}
