/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import userinterface.DoctorRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Medicine.Medicine;
import Business.Medicine.MedicineDirectory;
import Business.Network.Network;
import Business.Order.Order;
import Business.Order.OrderDirectory;

import Business.Organization.Organization;
import Business.Organization.PharmacistOrganization;
import Business.Pharmacy.Pharmacy;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CustomerWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class RequestMedicinesJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    
    private UserAccount userAccount;
    private EcoSystem system;
    private Pharmacy phar;
    private OrderDirectory orderD;
    private MedicineDirectory med;
    ArrayList<Order> finallist ;
    ArrayList<Order>  o = new ArrayList<Order>();
    // List<Order> o = new ArrayList<Order>();
    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestMedicinesJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
       
        this.userAccount = account;
        this.system=system;
        phar= new Pharmacy();
        orderD = new OrderDirectory();
       // valueLabel.setText(enterprise.getName());
        populateComboBox();
       
        
        
    }

    
     private void populateComboBox() {
        RegionCombo.removeAllItems();
        enterpriseCombo.removeAllItems();
        ChooseMedCombo.removeAllItems();
        BrandComboBox.removeAllItems();
        int Price=0;
        for (Network network : system.getNetworkList()) {
            RegionCombo.addItem(network);
        }
        
        
        for(Medicine medi : med.getMedicineList()){
             ChooseMedCombo.addItem(medi);
             BrandComboBox.addItem(medi.getBrand());
             }
        

         for (Network network : system.getNetworkList()) {
           //   RegionCombo.addItem(network);
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                Enterprise.EnterpriseType  type =enterprise.getEnterpriseType();
            if(type.equals(type.Pharmacy))
            enterpriseCombo.addItem(enterprise);
            }
        }
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        RegionCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        enterpriseCombo = new javax.swing.JComboBox();
        backJButton = new javax.swing.JButton();
        requestTestJButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ChooseMedCombo = new javax.swing.JComboBox();
        Medicinetxt = new javax.swing.JLabel();
        Quantitytxt = new javax.swing.JLabel();
        Qtyxt = new javax.swing.JTextField();
        AddtoCart = new javax.swing.JButton();
        BuyNow = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Pricetxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        BrandComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Request Medicines");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 730, 48);

        RegionCombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RegionCombo.setForeground(new java.awt.Color(0, 51, 51));
        jPanel2.add(RegionCombo);
        RegionCombo.setBounds(138, 59, 90, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Region");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(48, 59, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EnterPrise");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(460, 60, 90, 30);

        enterpriseCombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enterpriseCombo.setForeground(new java.awt.Color(0, 51, 51));
        enterpriseCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseComboActionPerformed(evt);
            }
        });
        jPanel2.add(enterpriseCombo);
        enterpriseCombo.setBounds(570, 60, 110, 30);

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(0, 51, 51));
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel2.add(backJButton);
        backJButton.setBounds(38, 462, 87, 37);

        requestTestJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        requestTestJButton.setForeground(new java.awt.Color(0, 51, 51));
        requestTestJButton.setText("View Cart");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        jPanel2.add(requestTestJButton);
        requestTestJButton.setBounds(600, 460, 99, 37);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3), "MedicineDetails", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        ChooseMedCombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChooseMedCombo.setForeground(new java.awt.Color(0, 51, 51));
        ChooseMedCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", " " }));

        Medicinetxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Medicinetxt.setForeground(new java.awt.Color(255, 255, 255));
        Medicinetxt.setText("Medicine");

        Quantitytxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Quantitytxt.setForeground(new java.awt.Color(255, 255, 255));
        Quantitytxt.setText("Quantity");

        Qtyxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Qtyxt.setForeground(new java.awt.Color(0, 51, 51));

        AddtoCart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddtoCart.setForeground(new java.awt.Color(0, 51, 51));
        AddtoCart.setText("Add to Cart");
        AddtoCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddtoCartActionPerformed(evt);
            }
        });

        BuyNow.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BuyNow.setForeground(new java.awt.Color(0, 51, 51));
        BuyNow.setText("Buy Now");
        BuyNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyNowActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Price");

        Pricetxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Pricetxt.setForeground(new java.awt.Color(0, 51, 51));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setText("Price Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Brand");

        BrandComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BrandComboBox.setForeground(new java.awt.Color(0, 51, 51));
        BrandComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(BuyNow))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Quantitytxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Medicinetxt, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChooseMedCombo, 0, 1, Short.MAX_VALUE)
                    .addComponent(Qtyxt, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(Pricetxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(BrandComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 146, Short.MAX_VALUE)
                    .addComponent(AddtoCart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BrandComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Medicinetxt)
                    .addComponent(ChooseMedCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quantitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Qtyxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddtoCart)
                    .addComponent(BuyNow))
                .addGap(24, 24, 24))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(20, 120, 689, 328);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PatientRole/3d_dna-1680x1050.jpg"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 770, 540);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
//        if(finallist.size() == 0){
//        JOptionPane.showMessageDialog(RegionCombo, "The cart is empty");
//        }
         OrderDetailsJPanel orderDetail = new OrderDetailsJPanel(userProcessContainer,finallist,userAccount,system);
        userProcessContainer.add("OrderDetailsPanel", orderDetail);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void AddtoCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddtoCartActionPerformed
        // TODO add your handling code here:
         float Price = 0, updatedPrice = 0;
         String Brand ="";
       //  ArrayList<String> list = new ArrayList<>();

        Medicine m = (Medicine) ChooseMedCombo.getSelectedItem();
//        if(enterpriseCombo.getSelectedItem().equals("") 
//                || Qtyxt.getText().equals("")
//                || Pricetxt.getText().equals("")){
//        JOptionPane.showMessageDialog(RegionCombo, "Please complete the details.");
//        return;
//        }
        int qty = Integer.parseInt(Qtyxt.getText());
        for (Medicine medi : med.getMedicineList()) {
            if (m.getSaltname().equals(medi.getSaltname())) {
                Price = medi.getPrice() * qty;
                Pricetxt.setText(String.valueOf(Price) + "$");
                Pricetxt.setEnabled(false);
                Brand = (String) BrandComboBox.getSelectedItem();
            }
        }
        Order order = orderD.AddOrder(m.getSaltname(), Price, qty,Brand);

        o.add(order);
        for (int i = 0; i < o.size(); i++) {
            if (m.getSaltname().equalsIgnoreCase(o.get(i).getItem().getProduct_name())) {
              //  updatedPrice = o.get(i).getItem().getSalesPrice()+Price;

                o.set(i, order);
            }

        }
        HashSet<Order> listToSet = new HashSet<Order>(o);
        finallist = new ArrayList<Order>(listToSet);

    }//GEN-LAST:event_AddtoCartActionPerformed

    private void BuyNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyNowActionPerformed
        // TODO add your handling code here:
        float Price=0;
        String Brand = "";
        finallist =new ArrayList<>();
        try{
        Medicine m = (Medicine) ChooseMedCombo.getSelectedItem();

        int qty = Integer.parseInt(Qtyxt.getText());
        for (Medicine medi : med.getMedicineList()) {
            if (m.getSaltname().equals(medi.getSaltname())) {
                Price = medi.getPrice() * qty;
                Brand = (String) BrandComboBox.getSelectedItem();
               // Pricetxt.setText(String.valueOf(Price) + "$");
                //Pricetxt.setEnabled(false);
            }
        }
        
        Order order = orderD.AddOrder(m.getSaltname(), Price, qty,Brand);

        finallist.add(order);

         if(!((m.equals("") || qty==0)|| Pricetxt.getText().equals("")))
        {
        OrderDetailsJPanel orderDetail = new OrderDetailsJPanel(userProcessContainer,finallist,userAccount,system);
        userProcessContainer.add("OrderDetailsPanel", orderDetail);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        else
            JOptionPane.showMessageDialog(null,"Please do the Price Check!");
        }catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null,"Please choose medicines to buy!");
        }
        
    }//GEN-LAST:event_BuyNowActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        Medicine medicine= (Medicine) ChooseMedCombo.getSelectedItem();
        float Price=0;
         for(Medicine medi : med.getMedicineList())
         {
             if(medicine.getSaltname().equals(medi.getSaltname())){
                 Price = medi.getPrice();
                 Pricetxt.setText(String.valueOf(Price)+"$  per medicine");
         }  
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void enterpriseComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseComboActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddtoCart;
    private javax.swing.JComboBox BrandComboBox;
    private javax.swing.JButton BuyNow;
    private javax.swing.JComboBox ChooseMedCombo;
    private javax.swing.JLabel Medicinetxt;
    private javax.swing.JTextField Pricetxt;
    private javax.swing.JTextField Qtyxt;
    private javax.swing.JLabel Quantitytxt;
    private javax.swing.JComboBox RegionCombo;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox enterpriseCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton requestTestJButton;
    // End of variables declaration//GEN-END:variables
}
