/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManageMedicineInventory;

import userinterface.ManageMedicineInventory.ViewMedicineInventoryPage;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Medicine.Medicine;
import Business.Medicine.MedicineDirectory;
import static Business.Medicine.MedicineDirectory.ManufacturerMedicineList;
import Business.Network.Network;
import Business.Organization.ManufacturingManagerOrganization;
import Business.Organization.Organization;
import static Business.Organization.Organization.Type.SupplyManager;
import Business.Organization.PharmacistOrganization;
import Business.Organization.SupplyManagerOrganization;
import Business.Supplier.Supplier;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.BookDirectory;
import userinterface.PatientRole.ViewMedicineDetailsPage;

/**
 *
 * @author Vaishali Tripathi
 */
public class AddToInventoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddToInventoryJPanel
     */
    private Enterprise enterprise;
    //private Supplier supp;
    //private DataReader commentReader;
    private MedicineDirectory b;
    private BookDirectory b1;
    private Enterprise e;
    private Organization org;

    public AddToInventoryJPanel(JPanel userProcessContainer, Organization org, Enterprise e, MedicineDirectory med) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.e = e;
        this.b = med;
        this.org = org;
        brandNameTxt.setEditable(false);
        brandNameTxt.setForeground(Color.gray);
        medNameTxt.setEditable(false);
        medNameTxt.setForeground(Color.gray);
        populateComboBox();
    }

    private void populateComboBox() {
        brandNameCombo.removeAllItems();

        SaltNameCombo.removeAllItems();
        int Price = 0;

        for (Medicine medi : b.getManufacturerMedicineList()) {
            SaltNameCombo.addItem(medi);
        }
        SaltNameCombo.addItem("Other");
        for (Medicine medi : b.getManufacturerMedicineList()) {
            brandNameCombo.addItem(medi.getBrand());
        }
        brandNameCombo.addItem("Other");

        for (Medicine.MedicineType type : Medicine.MedicineType.values()) {
            TypeCombo.addItem(type);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userProcessContainer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PriceTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Noofunitstxt = new javax.swing.JTextField();
        TypeCombo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        addMedBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        viewInvenBtn = new javax.swing.JButton();
        SaltNameCombo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        brandNameCombo = new javax.swing.JComboBox<>();
        composition1Txt = new javax.swing.JTextField();
        composition2Txt = new javax.swing.JTextField();
        composition3Txt = new javax.swing.JTextField();
        brandNameTxt = new javax.swing.JTextField();
        medNameTxt = new javax.swing.JTextField();
        diseasename = new javax.swing.JTextField();

        jLabel1.setText("  Add Medicines To Inventory");

        jLabel2.setText("Medicine Name ");

        jLabel3.setText("Salt Composition ");

        jLabel4.setText("Price Per Medicine");

        jLabel5.setText("Type");

        jLabel6.setText("Number of Units");

        addMedBtn.setText("ADD");
        addMedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMedBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Disease Name");

        viewInvenBtn.setText("View Inventory");
        viewInvenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInvenBtnActionPerformed(evt);
            }
        });

        SaltNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaltNameComboActionPerformed(evt);
            }
        });

        jLabel8.setText("Brand");

        brandNameCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brandNameComboMouseClicked(evt);
            }
        });
        brandNameCombo.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                brandNameComboInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        brandNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandNameComboActionPerformed(evt);
            }
        });

        brandNameTxt.setText("Other");
        brandNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandNameTxtActionPerformed(evt);
            }
        });

        medNameTxt.setText("Other");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(backBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addMedBtn)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PriceTxt)
                                    .addComponent(Noofunitstxt)
                                    .addComponent(TypeCombo, 0, 314, Short.MAX_VALUE)
                                    .addComponent(SaltNameCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(composition2Txt)
                                    .addComponent(brandNameCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(diseasename)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(40, 40, 40)
                        .addComponent(composition1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(viewInvenBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(composition3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(medNameTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(brandNameTxt, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(brandNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaltNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(composition1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(composition2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(composition3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Noofunitstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diseasename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(addMedBtn)
                    .addComponent(viewInvenBtn)))
        );

        javax.swing.GroupLayout userProcessContainerLayout = new javax.swing.GroupLayout(userProcessContainer);
        userProcessContainer.setLayout(userProcessContainerLayout);
        userProcessContainerLayout.setHorizontalGroup(
            userProcessContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userProcessContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        userProcessContainerLayout.setVerticalGroup(
            userProcessContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userProcessContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userProcessContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userProcessContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addMedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedBtnActionPerformed
        // TODO add your handling code here:
        try {
            String brand;

            if (String.valueOf(brandNameCombo.getSelectedItem()).equalsIgnoreCase("Other")) {
                brandNameTxt.setEditable(true);
                brand = brandNameTxt.getText();
                brandNameTxt.setForeground(Color.black);

            } else {
                brand = String.valueOf(brandNameCombo.getSelectedItem());
            }

            String SaltName;
            if (String.valueOf(SaltNameCombo.getSelectedItem()).equals("Other")) {
                medNameTxt.setEditable(true);
                SaltName = medNameTxt.getText();
                medNameTxt.setForeground(Color.black);
            } else {
                SaltName = String.valueOf(SaltNameCombo.getSelectedItem());
            }

            int Price = Integer.parseInt(PriceTxt.getText());

            String saltc1 = composition1Txt.getText();
            String saltc2 = composition2Txt.getText();
            String saltc3 = composition3Txt.getText();

            String type = TypeCombo.getSelectedItem().toString();
            int units = Integer.parseInt(Noofunitstxt.getText());
            String disease = diseasename.getText();

            String[] s = new String[9];

            s[0] = brand;
            s[1] = SaltName;
            s[2] = saltc1;
            s[3] = saltc2;
            s[4] = saltc3;
            s[5] = type;
            s[6] = disease;
            s[7] = String.valueOf(units);
            s[8] = String.valueOf(Price);

            for (Organization organization : e.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof ManufacturingManagerOrganization) {
                    boolean flag = false;
                    for (Medicine m : b.getManufacturerMedicineList()) {

                        if (m.getBrand().equalsIgnoreCase(brand)
                                && m.getSaltComposition1().equalsIgnoreCase(saltc1)
                                && m.getSaltComposition2().equalsIgnoreCase(saltc2)
                                && m.getSaltComposition3().equalsIgnoreCase(saltc3)
                                && m.getSaltname().equalsIgnoreCase(SaltName)
                                && m.getDisease().equalsIgnoreCase(disease)
                                && m.getType().equalsIgnoreCase(type)
                                && m.getPrice() == (Price)) {
                                m.setUnits(m.getUnits() + units);
                                JOptionPane.showMessageDialog(this, "Units Updated");
                                flag = true;
                                break;
                            }}
                    if (flag == false){
                    for (Medicine m : b.getManufacturerMedicineList()) {
                        if (m.getBrand().equalsIgnoreCase(brand)
                                && m.getSaltComposition1().equalsIgnoreCase(saltc1)
                                && m.getSaltComposition2().equalsIgnoreCase(saltc2)
                                && m.getSaltComposition3().equalsIgnoreCase(saltc3)
                                && m.getSaltname().equalsIgnoreCase(SaltName)
                                && m.getDisease().equalsIgnoreCase(disease)
                                && m.getType().equalsIgnoreCase(type)
                                && m.getPrice() != (Price)) {int selectionButton = JOptionPane.YES_NO_OPTION;
                             int selectionResult = JOptionPane.showConfirmDialog(null, "Price has been changed. Do you want to update the inventory price?","Warning",selectionButton);
                            if (selectionResult == JOptionPane.YES_OPTION) {
                                m.setUnits(m.getUnits() + units);
                                m.setPrice(Price);
                                JOptionPane.showMessageDialog(this, "Units and price updated");
                                flag = true;    
                            }
                            break;
                            }}}
                    if(flag==false){
                        b.AddManufacturerMedicine(s);
                        JOptionPane.showMessageDialog(this, "Medicines added successfully!");
                    break;
                        
                    }
                    
                    }
                    
                    

                 else if (organization instanceof PharmacistOrganization) {
                    
                    boolean flag = false;
                    for (Medicine m : b.getMedicineList()) {

                        if (m.getBrand().equalsIgnoreCase(brand)
                                && m.getSaltComposition1().equalsIgnoreCase(saltc1)
                                && m.getSaltComposition2().equalsIgnoreCase(saltc2)
                                && m.getSaltComposition3().equalsIgnoreCase(saltc3)
                                && m.getSaltname().equalsIgnoreCase(SaltName)
                                && m.getDisease().equalsIgnoreCase(disease)
                                && m.getType().equalsIgnoreCase(type)
                                && m.getPrice() == (Price)) {

                            
                                m.setUnits(m.getUnits() + units);

                                JOptionPane.showMessageDialog(this, "Units Updated");
                                flag = true;
                                break;
                            }}
                    if (flag == false){
                    for (Medicine m : b.getMedicineList()) {
                        if (m.getBrand().equalsIgnoreCase(brand)
                                && m.getSaltComposition1().equalsIgnoreCase(saltc1)
                                && m.getSaltComposition2().equalsIgnoreCase(saltc2)
                                && m.getSaltComposition3().equalsIgnoreCase(saltc3)
                                && m.getSaltname().equalsIgnoreCase(SaltName)
                                && m.getDisease().equalsIgnoreCase(disease)
                                && m.getType().equalsIgnoreCase(type)
                                && m.getPrice() != (Price)) {int selectionButton = JOptionPane.YES_NO_OPTION;
                             int selectionResult = JOptionPane.showConfirmDialog(null, "Price has been changed. Do you want to update the inventory price?","Warning",selectionButton);
                            if (selectionResult == JOptionPane.YES_OPTION) {
                                m.setUnits(m.getUnits() + units);
                                m.setPrice(Price);
                                JOptionPane.showMessageDialog(this, "Units and price updated");
                                flag = true;    
                            }
                            break;
                            }}}
                    if(flag==false){
                        b.AddMedicine(s);
                        JOptionPane.showMessageDialog(this, "Medicines added successfully!");
                    break;
                        
                    }
                    
                    
                }
            }

        } catch (NumberFormatException e) {
            if (medNameTxt.getText().equals("") || brandNameTxt.getText().equals("") || PriceTxt.getText().equals("") || composition1Txt.getText().equals("")
                    || composition2Txt.getText().equals("") || composition3Txt.getText().equals("") || Noofunitstxt.getText().equals("") || diseasename.getText().equals("")) {
                JOptionPane.showMessageDialog(TypeCombo, "All the details are required.");
                return;
            }
            JOptionPane.showMessageDialog(TypeCombo, "Please check the input format.");

        }
    }//GEN-LAST:event_addMedBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backBtnActionPerformed

    private void viewInvenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInvenBtnActionPerformed
        // TODO add your handling code here:
        ViewMedicineInventoryPage view = new ViewMedicineInventoryPage(userProcessContainer, org, e, b);
        userProcessContainer.add("ViewProductDetailJPanelSupplier", view);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewInvenBtnActionPerformed

    private void brandNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandNameTxtActionPerformed

    private void brandNameComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandNameComboMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_brandNameComboMouseClicked

    private void brandNameComboInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_brandNameComboInputMethodTextChanged

    }//GEN-LAST:event_brandNameComboInputMethodTextChanged

    private void brandNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandNameComboActionPerformed
        // TODO add your handling code here:
        if (String.valueOf(brandNameCombo.getSelectedItem()).equalsIgnoreCase("Other")) {
            brandNameTxt.setEnabled(true);
            brandNameTxt.setEditable(true);
            brandNameCombo.setForeground(Color.gray);
            brandNameTxt.setText("");
            brandNameTxt.setForeground(Color.black);
        } else {
            brandNameTxt.setText("Other");
            brandNameTxt.setEnabled(false);
            brandNameTxt.setForeground(Color.gray);
        }
    }//GEN-LAST:event_brandNameComboActionPerformed

    private void SaltNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaltNameComboActionPerformed
        // TODO add your handling code here:
        if (String.valueOf(SaltNameCombo.getSelectedItem()).equalsIgnoreCase("Other")) {
            medNameTxt.setEnabled(true);
            medNameTxt.setEditable(true);
            SaltNameCombo.setForeground(Color.gray);
            medNameTxt.setText("");
            medNameTxt.setForeground(Color.black);
        } else {
            medNameTxt.setText("Other");
            medNameTxt.setEnabled(false);
            medNameTxt.setForeground(Color.gray);
        }

    }//GEN-LAST:event_SaltNameComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Noofunitstxt;
    private javax.swing.JTextField PriceTxt;
    private javax.swing.JComboBox<Object> SaltNameCombo;
    private javax.swing.JComboBox TypeCombo;
    private javax.swing.JButton addMedBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> brandNameCombo;
    private javax.swing.JTextField brandNameTxt;
    private javax.swing.JTextField composition1Txt;
    private javax.swing.JTextField composition2Txt;
    private javax.swing.JTextField composition3Txt;
    private javax.swing.JTextField diseasename;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField medNameTxt;
    private javax.swing.JPanel userProcessContainer;
    private javax.swing.JButton viewInvenBtn;
    // End of variables declaration//GEN-END:variables
}
