/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManageMedicineInventory;


import userinterface.ManageMedicineInventory.ViewMedicineInventoryPage;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Medicine.Medicine;
import Business.Medicine.MedicineDirectory;
import Business.Network.Network;
import Business.Organization.ManufacturingManagerOrganization;
import Business.Organization.Organization;
import static Business.Organization.Organization.Type.SupplyManager;
import Business.Organization.PharmacistOrganization;
import Business.Organization.SupplyManagerOrganization;
import Business.Pharmacy.Pharmacy;
import Business.Supplier.Supplier;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MedicineSupplyWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.BookDirectory;
import userinterface.PatientRole.ViewMedicineDetailsPage;
/**
 *
 * @author Vaishali Tripathi
 */
public class RequestMedicineSupplyJPanel extends javax.swing.JPanel {

    private MedicineDirectory b;
    private BookDirectory b1;
    private Enterprise e;
    private Organization org;
    private final JPanel userProcessContainer;
    private UserAccount user;
    private EcoSystem system;
    /**
     * Creates new form SupplyManagerRequestSupplyJPanel
     */
    public RequestMedicineSupplyJPanel(JPanel userProcessContainer,Organization org,Enterprise e, MedicineDirectory med,EcoSystem system, UserAccount user) {
        initComponents();
       brandNameTxt.setEditable(false);
       brandNameTxt.setForeground(Color.gray);
       medNameTxt.setEditable(false);
       medNameTxt.setForeground(Color.gray);
     
       this.userProcessContainer=userProcessContainer;
       this.e=e;
       this.b = med;
       this.org = org;
       this.user = user;
       this.system = system;
  populateComboBox();
       //phar =new Pharmacy();
       populateTable();

    }
     private void populateComboBox() {
        brandNameCombo.removeAllItems();
        
        SaltNameCombo.removeAllItems();
        int Price=0;
              
        for(Medicine medi : b.getMedicineList()){
             SaltNameCombo.addItem(medi);
             }
        SaltNameCombo.addItem("Other");
        for(Medicine medi : b.getMedicineList()){
             brandNameCombo.addItem(medi.getBrand());
             }
        brandNameCombo.addItem("Other");
        
        for (Medicine.MedicineType type : Medicine.MedicineType.values()) {
           TypeCombo.addItem(type);
        } 
         System.out.println(system.getNetworkList().size());
        for(Network net : system.getNetworkList()){
             netowrkListCombo.addItem(net);
             }
     }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : user.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[11];
            row[0] = ((MedicineSupplyWorkRequest) request);
            row[1] = ((MedicineSupplyWorkRequest) request).getBrand();
            row[2] = ((MedicineSupplyWorkRequest) request).getQuantity();
            row[3] = ((MedicineSupplyWorkRequest) request).getPrice();
            row[4] = ((MedicineSupplyWorkRequest) request).getSaltc1();
            row[5] = ((MedicineSupplyWorkRequest) request).getSaltc3();
            row[6] = ((MedicineSupplyWorkRequest) request).getSaltc3();
            row[7] = ((MedicineSupplyWorkRequest) request).getMedType();
            row[8] = ((MedicineSupplyWorkRequest) request).getDiseaseName();
            row[9] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[10] = request.getStatus();
                        
            model.addRow(row);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        placeMedSuppReqBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        suppliernametxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        netowrkListCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        medNameTxt = new javax.swing.JTextField();
        diseasename = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        SaltNameCombo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        brandNameCombo = new javax.swing.JComboBox<>();
        composition1Txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        composition2Txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        composition3Txt = new javax.swing.JTextField();
        PriceTxt = new javax.swing.JTextField();
        brandNameTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Noofunitstxt = new javax.swing.JTextField();
        TypeCombo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        enterpriseList = new javax.swing.JComboBox<>();
        orgCombo = new javax.swing.JComboBox<>();
        addToInventoryBtn = new javax.swing.JButton();

        jLabel1.setText("Request For Supply");

        placeMedSuppReqBtn.setText("Place Request");
        placeMedSuppReqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeMedSuppReqBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Medicine Name", "Brand", "Quantity", "Price", "Salt 1", "Salt 2", "Salt 3", "Type", "Disease", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        netowrkListCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netowrkListComboActionPerformed(evt);
            }
        });

        jLabel6.setText("From Network");

        medNameTxt.setText("Other");

        jLabel7.setText("Disease Name");

        SaltNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaltNameComboActionPerformed(evt);
            }
        });

        jLabel8.setText("Brand");

        brandNameCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brandNameComboMouseClicked(evt);
            }
        });
        brandNameCombo.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                brandNameComboInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        brandNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandNameComboActionPerformed(evt);
            }
        });

        jLabel2.setText("Medicine Name ");

        jLabel3.setText("Salt Composition ");

        brandNameTxt.setText("Other");
        brandNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandNameTxtActionPerformed(evt);
            }
        });

        jLabel4.setText("Price Per Medicine");

        jLabel5.setText("Type");

        jLabel9.setText("Number of Units");

        enterpriseList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseListActionPerformed(evt);
            }
        });

        orgCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgComboActionPerformed(evt);
            }
        });

        addToInventoryBtn.setText("Add to Inventory");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(suppliernametxt, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addGap(533, 533, 533))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(111, 111, 111)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Noofunitstxt, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TypeCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 184, Short.MAX_VALUE)
                                            .addComponent(composition2Txt, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PriceTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SaltNameCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(brandNameCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(diseasename)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(40, 40, 40)
                                        .addComponent(composition1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel6)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(backBtn)
                                        .addGap(126, 126, 126)
                                        .addComponent(placeMedSuppReqBtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(netowrkListCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(enterpriseList, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(medNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brandNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(composition3Txt, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(orgCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addToInventoryBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(suppliernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addToInventoryBtn))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(brandNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaltNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(composition1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(composition2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(composition3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Noofunitstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diseasename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(netowrkListCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orgCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placeMedSuppReqBtn)
                    .addComponent(backBtn))
                .addGap(58, 58, 58))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void placeMedSuppReqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeMedSuppReqBtnActionPerformed
        
        try {
            
        
       String brand;
        
        if(String.valueOf(brandNameCombo.getSelectedItem()).equalsIgnoreCase("Other"))
        { brandNameTxt.setEditable(true);
            brand = brandNameTxt.getText();
        brandNameTxt.setForeground(Color.black);
            
            }
        else
         brand = String.valueOf(brandNameCombo.getSelectedItem());
        
        
        String SaltName;
                if(String.valueOf(SaltNameCombo.getSelectedItem()).equals("Other"))
                {medNameTxt.setEditable(true);
                    SaltName = medNameTxt.getText();
                 medNameTxt.setForeground(Color.black);}
                else
        SaltName = String.valueOf(SaltNameCombo.getSelectedItem());
       
                int Price = Integer.parseInt(PriceTxt.getText());
        
        
        
        String saltc1 = composition1Txt.getText();
        String saltc2 = composition2Txt.getText();
        String saltc3 = composition3Txt.getText();
        
        
        String type =  TypeCombo.getSelectedItem().toString();
        int units = Integer.parseInt(Noofunitstxt.getText());
        String disease = diseasename.getText();
        
        MedicineSupplyWorkRequest request = new MedicineSupplyWorkRequest();
        request.setMedName(SaltName);
        request.setMedType(type);
        request.setBrand(brand);
        request.setPrice(Price);
        request.setQuantity(units);
        request.setDiseaseName(disease);
        request.setSaltc1(saltc1);
        request.setSaltc2(saltc2);
        request.setSaltc3(saltc3);
        request.setMedType(type);
        request.setSender(user);
        request.setStatus("Sent");
                System.out.println("chal yaha tak to aaya "+this.org);

        Organization org = null;
        Enterprise e = (Enterprise) enterpriseList.getSelectedItem();
        Organization o = (Organization) orgCombo.getSelectedItem();
        for (Organization organization : e.getOrganizationDirectory().getOrganizationList()){
            
            if(this.org instanceof PharmacistOrganization && organization instanceof SupplyManagerOrganization)
            
//            if (organization instanceof SupplyManagerOrganization)
            {
                org = organization;
                System.out.println("Yeah bitches!!");
                JOptionPane.showMessageDialog(TypeCombo, "Order Placed!");
                break;
            }
            else if(this.org instanceof SupplyManagerOrganization && o instanceof ManufacturingManagerOrganization)
                
//                if(organization instanceof ManufacturingManagerOrganization)
                {
                org = o;
                //System.out.println("Yeah bitches!!");
                JOptionPane.showMessageDialog(TypeCombo, "Order Placed!");
                break;
            }
            else
            {JOptionPane.showMessageDialog(TypeCombo, "Please select the correct receiver!");
                break;}
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            user.getWorkQueue().getWorkRequestList().add(request);
            System.out.println("Yeah bitches!!");
        }
        populateTable();
        } 
        catch (NumberFormatException e) {
        if(medNameTxt.getText().equals("")||brandNameTxt.getText().equals("")||PriceTxt.getText().equals("")||composition1Txt.getText().equals("")
                ||composition2Txt.getText().equals("")||composition3Txt.getText().equals("")||Noofunitstxt.getText().equals("")||diseasename.getText().equals("")){
            JOptionPane.showMessageDialog(TypeCombo, "All the details are required.");
            return;
        }
        JOptionPane.showMessageDialog(TypeCombo, "Please check the input format.");
        
        }
        
        
    }//GEN-LAST:event_placeMedSuppReqBtnActionPerformed

    private void netowrkListComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netowrkListComboActionPerformed
        // TODO add your handling code here:
        Network network =  (Network) netowrkListCombo.getSelectedItem();
        for(Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()){
             enterpriseList.addItem(ent);
             }
    }//GEN-LAST:event_netowrkListComboActionPerformed

    private void SaltNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaltNameComboActionPerformed
        // TODO add your handling code here:
        if(String.valueOf(SaltNameCombo.getSelectedItem()).equalsIgnoreCase("Other"))
        { medNameTxt.setEnabled(true);
            medNameTxt.setEditable(true);
            SaltNameCombo.setForeground(Color.gray);
            medNameTxt.setText("");
            medNameTxt.setForeground(Color.black);
        }
        else
        { medNameTxt.setText("Other");
            medNameTxt.setEnabled(false);
            medNameTxt.setForeground(Color.gray);}

    }//GEN-LAST:event_SaltNameComboActionPerformed

    private void brandNameComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandNameComboMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_brandNameComboMouseClicked

    private void brandNameComboInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_brandNameComboInputMethodTextChanged

    }//GEN-LAST:event_brandNameComboInputMethodTextChanged

    private void brandNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandNameComboActionPerformed
        // TODO add your handling code here:
        if(String.valueOf(brandNameCombo.getSelectedItem()).equalsIgnoreCase("Other"))
        { brandNameTxt.setEnabled(true);
            brandNameTxt.setEditable(true);
            brandNameCombo.setForeground(Color.gray);
            brandNameTxt.setText("");
            brandNameTxt.setForeground(Color.black);
        }
        else
        {brandNameTxt.setText("Other");
            brandNameTxt.setEnabled(false);
            brandNameTxt.setForeground(Color.gray);}
    }//GEN-LAST:event_brandNameComboActionPerformed

    private void brandNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandNameTxtActionPerformed

    private void enterpriseListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseListActionPerformed
        // TODO add your handling code here:
        Enterprise e =  (Enterprise) enterpriseList.getSelectedItem();
        for(Organization ent : e.getOrganizationDirectory().getOrganizationList()){
             orgCombo.addItem(ent);
             }
    }//GEN-LAST:event_enterpriseListActionPerformed

    private void orgComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgComboActionPerformed
        // TODO add your handling code here:
//        Organization o = (Organization) orgCombo.getSelectedItem();
        
    }//GEN-LAST:event_orgComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Noofunitstxt;
    private javax.swing.JTextField PriceTxt;
    private javax.swing.JComboBox<Object> SaltNameCombo;
    private javax.swing.JComboBox TypeCombo;
    private javax.swing.JButton addToInventoryBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> brandNameCombo;
    private javax.swing.JTextField brandNameTxt;
    private javax.swing.JTextField composition1Txt;
    private javax.swing.JTextField composition2Txt;
    private javax.swing.JTextField composition3Txt;
    private javax.swing.JTextField diseasename;
    private javax.swing.JComboBox<Object> enterpriseList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField medNameTxt;
    private javax.swing.JComboBox<Object> netowrkListCombo;
    private javax.swing.JComboBox<Object> orgCombo;
    private javax.swing.JButton placeMedSuppReqBtn;
    private javax.swing.JLabel suppliernametxt;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
