/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManageMedicineInventory;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import userinterface.PatientRole.*;
import Business.Medicine.Medicine;
import Business.Medicine.MedicineDirectory;
import static Business.Medicine.MedicineDirectory.ManufacturerMedicineList;
import Business.Organization.ManufacturingManagerOrganization;
import Business.Organization.Organization;
import Business.Organization.PharmacistOrganization;
import Business.Organization.SupplyManagerOrganization;
import Business.Role.ManufacturingManagerRole;
import Business.Supplier.Supplier;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mantr
 */
public class ViewMedicineInventoryPage extends javax.swing.JPanel {

    /**
     * Creates new form ViewMedicineDetailsJPanel
     */
    private JPanel userProcessContainer;
    private Organization org;
    private Enterprise e;
    private MedicineDirectory med;
  public ViewMedicineInventoryPage(JPanel userProcessContainer, Organization org, Enterprise e, MedicineDirectory med) {
    
        initComponents();
        this.userProcessContainer = userProcessContainer;
       this.org=org;
       this.e = e;
      this.med = med;
        populateTable();
        System.out.println("org:"+org);
    }

    public void populateTable()
    {
    
DefaultTableModel model = (DefaultTableModel) SaltTable.getModel();

       model.setRowCount(0);
       // for (Organization organization : e.getOrganizationDirectory().getOrganizationList()){
            if (org instanceof ManufacturingManagerOrganization){
                System.out.println("The "+org+" size: "+med.getManufacturerMedicineList().size());
                  for(Medicine medi : med.getManufacturerMedicineList())
            
            {
                
               Object[] row = new Object[9];
           //row[0] = medi;
           row[0] = medi.getBrand();
           row[1]=medi;
           row[2]=medi.getSaltComposition1();
           row[3]=medi.getSaltComposition2();
           row[4]=medi.getSaltComposition3();
           row[5]=medi.getPrice();
           row[6]=medi.getType();
           row[7]=medi.getDisease();
           row[8]=medi.getUnits();
           

                      model.addRow(row);
            }
                System.out.println("Yeah bitches!!");
              //  break;
            }
            
            else if (org instanceof SupplyManagerOrganization){
                System.out.println("The "+org+" size: "+med.getSupplierMedicineList().size());
                  for(Medicine medi : med.getSupplierMedicineList())
            
            {
                
               Object[] row = new Object[9];
           //row[0] = medi;
           row[0] = medi.getBrand();
           row[1]=medi;
           row[2]=medi.getSaltComposition1();
           row[3]=medi.getSaltComposition2();
           row[4]=medi.getSaltComposition3();
           row[5]=medi.getPrice();
           row[6]=medi.getType();
           row[7]=medi.getDisease();
           row[8]=medi.getUnits();
           

                      model.addRow(row);
            }
                System.out.println("Yeah bitches!!");
             //   break;
            }
            
            
            
            else if(org instanceof PharmacistOrganization)
            {
                System.out.println("The "+org+" size: "+med.getSupplierMedicineList().size());
                for(Medicine medi : med.getMedicineList())
            
            {
                
               Object[] row = new Object[9];
           //row[0] = medi;
           row[0] = medi.getBrand();
           row[1]=medi;
           row[2]=medi.getSaltComposition1();
           row[3]=medi.getSaltComposition2();
           row[4]=medi.getSaltComposition3();
           row[5]=medi.getPrice();
           row[6]=medi.getType();
           row[7]=medi.getDisease();
           row[8]=medi.getUnits();
           

                      model.addRow(row);
            }
           //     break;
            }
       // }
        
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SaltTable = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Medicine Inventory");

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        SaltTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand", "Salt Name", "Composition 1", "Composition 2", "Composition 2", "Price per unit", "Type", "Disease", "No of Units"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(SaltTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 641, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JTable SaltTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
