/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import userinterface.pharmacistRole.*;
import Business.Employee.Employee;
import Business.Organization.Organization;
import static Business.Organization.Organization.Type.Pharmacy;
import Business.Organization.OrganizationDirectory;
import Business.Pharmacy.Pharmacy;
import Business.Pharmacy.PharmacyDirectory;
import Business.Role.Role;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Payal Zanwar
 */
public class DoctorLoginFormJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PharmacistLoginFormJPanel
     */
   // private JPanel PContainer;
    private Organization organization;
    private Employee employee;
    private Role role;
    private PharmacyDirectory pharmDir;
   
    public DoctorLoginFormJPanel(JPanel PContainer, Organization organization,Employee employee,Role role) {
        initComponents();
      //  organizationDir.getUserAccountDirectory().createUserAccount(userName, password, employee, role);
    this.employee=employee;
    this.PContainer=PContainer;
    this.role = role;
    this.organization=organization;
    pharmDir = new PharmacyDirectory();
    nametxt.setText(employee.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PContainer = new javax.swing.JPanel();
        ProcessContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CredJPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        passwordtxt = new javax.swing.JTextField();
        confirmpswdtxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BasicInfoJPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pharmacynametxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Emailidtxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Zipcodetxt = new javax.swing.JTextField();
        PharmLoctxt = new javax.swing.JTextField();
        submitbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(null);

        PContainer.setLayout(new java.awt.CardLayout());

        ProcessContainer.setLayout(null);

        jLabel1.setText("                           Doctor Sign Up");
        ProcessContainer.add(jLabel1);
        jLabel1.setBounds(160, 24, 494, 34);

        CredJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Credentials"));

        jLabel7.setText("Username");

        passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtxtActionPerformed(evt);
            }
        });

        confirmpswdtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpswdtxtActionPerformed(evt);
            }
        });

        jLabel10.setText("Password");

        jLabel8.setText("Confirm Password");

        javax.swing.GroupLayout CredJPanelLayout = new javax.swing.GroupLayout(CredJPanel);
        CredJPanel.setLayout(CredJPanelLayout);
        CredJPanelLayout.setHorizontalGroup(
            CredJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CredJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CredJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CredJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmpswdtxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        CredJPanelLayout.setVerticalGroup(
            CredJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CredJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CredJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CredJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CredJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmpswdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ProcessContainer.add(CredJPanel);
        CredJPanel.setBounds(100, 320, 573, 194);

        BasicInfoJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Basic Info"));

        jLabel2.setText("Name ");

        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });

        jLabel3.setText("Hospital Name");

        pharmacynametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmacynametxtActionPerformed(evt);
            }
        });

        jLabel5.setText("Doctor Location");

        jLabel4.setText("Zip Code");

        jLabel9.setText("Email ID");

        javax.swing.GroupLayout BasicInfoJPanelLayout = new javax.swing.GroupLayout(BasicInfoJPanel);
        BasicInfoJPanel.setLayout(BasicInfoJPanelLayout);
        BasicInfoJPanelLayout.setHorizontalGroup(
            BasicInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasicInfoJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BasicInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BasicInfoJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(Emailidtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                    .addGroup(BasicInfoJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(nametxt))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BasicInfoJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pharmacynametxt))
                    .addGroup(BasicInfoJPanelLayout.createSequentialGroup()
                        .addGroup(BasicInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(BasicInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Zipcodetxt)
                            .addComponent(PharmLoctxt))))
                .addGap(90, 90, 90))
        );
        BasicInfoJPanelLayout.setVerticalGroup(
            BasicInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasicInfoJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BasicInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BasicInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pharmacynametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BasicInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PharmLoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BasicInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Zipcodetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(BasicInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Emailidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ProcessContainer.add(BasicInfoJPanel);
        BasicInfoJPanel.setBounds(100, 60, 573, 250);

        submitbtn.setText("Submit");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        ProcessContainer.add(submitbtn);
        submitbtn.setBounds(360, 560, 83, 29);

        jButton1.setText(">>Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ProcessContainer.add(jButton1);
        jButton1.setBounds(100, 560, 89, 29);

        PContainer.add(ProcessContainer, "card2");

        add(PContainer);
        PContainer.setBounds(15, 16, 781, 763);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmpswdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpswdtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmpswdtxtActionPerformed

    private void passwordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtxtActionPerformed

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void pharmacynametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmacynametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pharmacynametxtActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        // TODO add your handling code here:
        
        String Pharname = pharmacynametxt.getText();
        String PharmLoc = PharmLoctxt.getText();
        String zip = Zipcodetxt.getText();
        String emailId = Emailidtxt.getText();
        String userName = usernametxt.getText();
        String password = passwordtxt.getText();
        String repassword = confirmpswdtxt.getText();
        
        
        pharmDir.createPharmacy(Pharname,PharmLoc,emailId,zip);
        this.organization.getUserAccountDirectory().createUserAccount(userName, password, this.employee, this.role);
        JOptionPane.showMessageDialog(PContainer, "Pharmacy created successfully!");
    }//GEN-LAST:event_submitbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PContainer.remove(this);
        CardLayout layout = (CardLayout) PContainer.getLayout();
        layout.previous(PContainer);
//        BasicInfoJPanel.remove(this);
//        CardLayout layoutA = (CardLayout) BasicInfoJPanel.getLayout();
//        layoutA.previous(BasicInfoJPanel);
//        CredJPanel.remove(this);
//        CardLayout layoutB = (CardLayout) BasicInfoJPanel.getLayout();
//        layoutB.previous(BasicInfoJPanel);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BasicInfoJPanel;
    private javax.swing.JPanel CredJPanel;
    private javax.swing.JTextField Emailidtxt;
    private javax.swing.JPanel PContainer;
    private javax.swing.JTextField PharmLoctxt;
    private javax.swing.JPanel ProcessContainer;
    private javax.swing.JTextField Zipcodetxt;
    private javax.swing.JTextField confirmpswdtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField passwordtxt;
    private javax.swing.JTextField pharmacynametxt;
    private javax.swing.JButton submitbtn;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
